name: TEST

on:
  push:

jobs:
  greet:
    runs-on: ubuntu-latest

    steps:
      - run: echo "Run Number is [ ${{ github.run_number }}]"
      - run: echo "Run Id is [ ${{ github.run_id }}]"
      - run: echo "Run attempt is [ ${{ github.run_attempt }}]"

